#############################################
## PROCESSO DE RESTAURAÇÃO UTILIZANDO RMAN ##
#############################################

## PROCEDIMENTO MANUAL

## REALIZAR UMA CÓPIA DE SEGURANÇA DO INIT/SPFILE DA BASE DE DADOS NO DIRETÓRIO DBS, INIT SERÁ EXCLUIDO NO DROP DA BASE
cp db_name.init db_name_copia_seguranca.init
cp db_name.spfile db_name_copia_seguranca.spfile

## ACESSAR A BASE E BAIXAR A INSTÂNCIA
sqlplus /as sysdba
shutdown immediate;

## SUBIR A BASE EM MODO RESTRITO PARA FAZER O DROP
sqlplus /as sysdba
startup mount restrict;
# VALIDAR SE ESTÁ NA BASE CORRETA ANTES DE FAZER O DROP (SHOW PARAMETER NAME)
drop database;

## REALIZAR O STARTUP DA BASE APÓS DROP
sqlplus /as sysdba
startup nomount;

## REALIZAR A RESTAURAÇÃO DO CONTROLFILE OBTIDO NO PROCESSO DE BKP DA BASE (BACKUP AS COPY CURRENT CONTROLFILE FORMAT '/CAMINHO_DO_BKP/CTL_DBNAME.BKP';)
. oraenv # SETAR O BANCO QUE SERÁ RESTAURADO
rman target / # ACESSAR O UTILITÁRIO RMAN
restore controlfile from '/caminho_do_bkp/ctl_dbname.bkp'; # COMANDO PARA RESTAURAR CONTROLFILE

## FIM DO PROCEDIMENTO MANUAL

##########################################################
## INSTRUÇÃO PARA AGENDAMENTO DA RESTAURAÇÃO EM CRONTAB ##
##########################################################
## OBS  : NO EXEMPLO EXCUÇÃO ESTÁ AGENDADA DIARIAMENTE AS 19H, ALTERAR CAMINHOS DE ACORDO COM AS CONFIGURAÇÕES DE INSTALAÇÃO DO BANCO ##
00 19 * * * /caminho_do_script/restore_rman.sh dbname /oracle_base/ /oracle_home/

## INICIO SHELL SCRIPT

## EXPORTA AS VÁRIAVEIS PARA EXECUÇÃO DA RESTAURAÇÃO ##
export ORACLE_SID=$1 ## COLETA SID
export ORACLE_BASE=$2 ## COLETA ORACLE BASE DE ACORDO COM LINHA DE CONFIGURAÇÃO DO CRON
export ORACLE_HOME=$3 ## COLETA ORACLE HOME DE ACORDO COM LINHA DE CONFIGURAÇÃO DO CRON
export DT='date +%a_%d%m' ## COLETA A DATA ATUAL
export PATH=$ORACLE_HOME/bin:$PATH ## VARIÁVEL DE AMBIENTE QUE CONTÉM OS DIRETÓRIOS EM QUE O ORACLE DATABASE PROCURA POR EXECUTÁVEIS E ARQUIVOS DE BIBLIOTECA

$ORACLE_HOME/bin/rman target / @caminho_do_script/restore_db_name.rman log='caminho_do_script/restore_db_name_$DT.log'

## FINALIZAÇÃO SHELL SCRIPT

####################################################################
## INICIO DA CRIAÇÃO DO SCRIPT .RMAN PARA EXECUÇÃO DA RESTAURAÇÃO ##
####################################################################

RUN {
CATALOG START WITH '/CAMINHO_DO_BKP/';
CROSSCHECK BACKUP;
DELETE EXPIRED BACKUP;
ALLOCATE CHANNEL CH1 DEVICE TYPE DISK;
SET NEWNAME FOR DATABASE TO '/CAMINHO_DOS_DATAFILES_DO_BANCO/%B';
SET NEWNAME FOR TEMPFILE TO '/CAMINHO_DOS_DATAFILES_DO_BANCO/TEMP.DBF';
RESTORE DATABASE;
SWITCH DATAFILE ALL;
RECOVER DATABASE;
}

## CATALOG START WITH '/CAMINHO_DO_BKP/'; ESSE COMANDO INDICA AO RMAN O CAMINHO ONDE ESTÃO LOCALIZADOS OS ARQUIVOS DE BACKUP QUE SERÃO CATALOGADOS. O RMAN IRÁ REGISTRAR ESSES BACKUPS EM SEU REPOSITÓRIO PARA QUE POSSAM SER UTILIZADOS POSTERIORMENTE.
## CROSSCHECK BACKUP; O COMANDO CROSSCHECK VERIFICA A EXISTÊNCIA FÍSICA DOS BACKUPS REGISTRADOS NO REPOSITÓRIO DO RMAN. ESSA VERIFICAÇÃO É FEITA COMPARANDO AS INFORMAÇÕES DO REPOSITÓRIO COM OS ARQUIVOS REAIS NO LOCAL ESPECIFICADO. NESTE CASO, O COMANDO CROSSCHECK BACKUP VERIFICA SE OS BACKUPS EXISTENTES AINDA ESTÃO ACESSÍVEIS.
## DELETE EXPIRED BACKUP; ESSE COMANDO REMOVE DO REPOSITÓRIO DO RMAN OS REGISTROS DE BACKUPS QUE JÁ ESTÃO EXPIRADOS OU NÃO ESTÃO MAIS ACESSÍVEIS. É UMA PRÁTICA COMUM EXECUTAR ESSA LIMPEZA PARA MANTER O REPOSITÓRIO ORGANIZADO E ATUALIZADO.
## ALLOCATE CHANNEL CH1 DEVICE TYPE DISK; O COMANDO ALLOCATE CHANNEL ALOCA UM CANAL PARA A EXECUÇÃO DAS OPERAÇÕES DE BACKUP E RESTAURAÇÃO. NESSE CASO, ESTÁ SENDO ALOCADO UM CANAL CHAMADO CH1 PARA UTILIZAR DISPOSITIVOS DE ARMAZENAMENTO EM DISCO (DEVICE TYPE DISK). É POSSÍVEL TER MÚLTIPLOS CANAIS PARA PARALELIZAR AS OPERAÇÕES.
## SET NEWNAME FOR DATABASE TO '/CAMINHO_DOS_DATAFILES_DO_BANCO/%B'; ESSE COMANDO DEFINE UM NOVO NOME PARA OS ARQUIVOS DE DADOS DO BANCO DE DADOS DURANTE A RESTAURAÇÃO. O CURINGA `%B` SERÁ SUBSTITUÍDO PELO NOME ORIGINAL DO ARQUIVO DE DADOS.
## SET NEWNAME FOR TEMPFILE TO '/CAMINHO_DOS_DATAFILES_DO_BANCO/TEMP.DBF'; ESSE COMANDO DEFINE UM NOVO NOME PARA O ARQUIVO TEMPORÁRIO DURANTE A RESTAURAÇÃO. O NOVO NOME ESPECIFICADO É '/CAMINHO_DOS_DATAFILES_DO_BANCO/TEMP.DBF'.
## RESTORE DATABASE; ESSE COMANDO REALIZA A RESTAURAÇÃO DO BANCO DE DADOS. O RMAN IRÁ UTILIZAR OS BACKUPS DISPONÍVEIS PARA RESTAURAR OS ARQUIVOS DE DADOS E DE CONTROLE DO BANCO DE DADOS.
## SWITCH DATAFILE ALL; ESSE COMANDO ALTERA A REFERÊNCIA DO RMAN PARA OS ARQUIVOS DE DADOS RESTAURADOS. ELE ATUALIZA O REGISTRO DO RMAN PARA APONTAR PARA OS ARQUIVOS RESTAURADOS EM VEZ DOS ARQUIVOS ANTIGOS.
## RECOVER DATABASE; ESSE COMANDO EXECUTA O PROCESSO DE RECUPERAÇÃO DO BANCO DE DADOS. O RMAN APLICARÁ OS REGISTROS DE REDO NECESSÁRIOS PARA GARANTIR A CONSISTÊNCIA DOS DADOS APÓS A RESTAURAÇÃO.

## APÓS RESTAURAÇÃO SERÁ NECESSÁRIO VALIDAR O LOCAL DOS REDOS, CASO NÃO ESTEJAM NO CAMINHO CORRETO, EXECUTAR O SEGUINTE PROCEDIMENTO
SELECT FILE#, MEMBER FROM V$REDOLOG; # VALIDA O CAMINHO DOS REDOS REALIZAR COMANDO COENCTADO NA BASE
ALTER DATABASE RENAME FILE 'CAMINHO_ANTIGO/REDO.LOG' TO 'CAMINHO_NOVO/REDO.LOG' # ALTERA O CAMINHO DO REDO, FAZER PARA TODOS LISTADOS

## FAZER A ABERTURA DA BASE APÓS VALIDAÇÃO DA EXECUÇÃO CORRETA DA RESTAURAÇÃO
ALTER DATABASE OPEN RESETLOGS;

## MAIS INFORMAÇÕES NA DOCUMENTAÇÃO OFICIAL
## https://docs.oracle.com/en/database/oracle/oracle-database/19/rcmrf/about-rman-commands.html#GUID-0385D88E-6D36-41AC-BEA0-DD7F5C97D253