#################################################
## EXECUÇÃO DE BKP FULL FÍSICO UTILIZANDO RMAN ##
#################################################

##################################################
## INSTRUÇÃO PARA AGENDAMENTO DO BKP EM CRONTAB ##
##################################################
## OBS  : NO EXEMPLO EXCUÇÃO ESTÁ AGENDADA DIARIAMENTE AS 19H, ALTERAR CAMINHOS DE ACORDO COM AS CONFIGURAÇÕES DE INSTALAÇÃO DO BANCO ##
00 19 * * * /caminho_do_script/backup_rman.sh dbname /oracle_base/ /oracle_home/

## INICIO SHELL SCRIPT

#!/bin/bash
# PARAMETROS
# 1 = INSTÂNCIA
# 2 = ORACLE BASE
# 3 = ORACLE HOME

## EXPORTA AS VÁRIAVEIS PARA EXECUÇÃO DO BKP RMAN ##
export ORACLE_SID=$1 ## COLETA SID
export ORACLE_BASE=$2 ## COLETA ORACLE BASE DE ACORDO COM LINHA DE CONFIGURAÇÃO DO CRON
export ORACLE_HOME=$3 ## COLETA ORACLE HOME DE ACORDO COM LINHA DE CONFIGURAÇÃO DO CRON
export DT='date +%a_%d%m' ## COLETA A DATA ATUAL
export PATH=$ORACLE_HOME/bin:$PATH ## VARIÁVEL DE AMBIENTE QUE CONTÉM OS DIRETÓRIOS EM QUE O ORACLE DATABASE PROCURA POR EXECUTÁVEIS E ARQUIVOS DE BIBLIOTECA

$ORACLE_HOME/bin/rman target / @caminho_do_script/backup_rman.rman log=/caminho_do_script/backup_rman_log_$DT.rman

## FINALIZAÇÃO SHELL SCRIPT

############################################################
## INICIO DA CRIAÇÃO DO SCRIPT .RMAN PARA EXECUÇÃO DO BKP ##
############################################################
## OBS: CRIAR O SCRIT .RMAN FORA DO .SH
## BLOCO DE COMANDOS PARA REALIZAÇÃO DO BKP RMAN FULL VERSÃO STANDARD
RUN {
   ALLOCATE CHANNEL CH1 DEVICE TYPE DISK;
   CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT '/CAMINHO_DO_BKP/FULL_%U_%S_%P';
   BACKUP AS COPY CURRENT CONTROLFILE FORMAT '/CAMINHO_DO_BKP/CTL_DBNAME.BKP';
   CONFIGURE CONTROLFILE AUTOBACKUP ON;
   BACKUP DATABASE PLUS ARCHIVELOG;
}

## BLOCO DE COMANDOS PARA REALIZAÇÃO DO BKP RMAN FULL VERSÃO ENTERPRISE
## PODE SER ALOCADO VÁRIOS CANAIS PARA EXECUÇÃO DO BKP

RUN {
   ALLOCATE CHANNEL CH1 DEVICE TYPE DISK FORMAT '/CAMINHO_DO_BKP/FULL_%U_%S_%P.BKP';
   ALLOCATE CHANNEL CH2 DEVICE TYPE DISK FORMAT '/CAMINHO_DO_BKP/FULL_%U_%S_%P.BKP';
   ALLOCATE CHANNEL CH3 DEVICE TYPE DISK FORMAT '/CAMINHO_DO_BKP/FULL_%U_%S_%P.BKP';
   ALLOCATE CHANNEL CH4 DEVICE TYPE DISK FORMAT '/CAMINHO_DO_BKP/FULL_%U_%S_%P.BKP';
   BACKUP DATABASE PLUS ARCHIVELOG FORMAT '/CAMINHO_DO_BKP/ARCHIVE_%D_%T_%S_%P.BKP';
   CONFIGURE CONTROLFILE AUTOBACKUP ON;
   RELEASE CHANNEL CH01;
   RELEASE CHANNEL CH02;
   RELEASE CHANNEL CH03;
   RELEASE CHANNEL CH04;
}

## EXEMPLO EXPLICA COMO REALIZAR O BKP EM DISCO LOCAL, SE O BKP É REALIZADO PARA TAPE É NECESSÁRIO OUTRAS CONFIGURAÇÕES
## RUN INDICA O INÍCIO DE UM BLOCO DE COMANDOS RMAN.
## ALLOCATE CHANNEL CH1 DEVICE TYPE DISK; ALOCA UM CANAL DE BACKUP CHAMADO CH1 PARA O TIPO DE DISPOSITIVO DISK (DISCO). ESSE COMANDO ESPECIFICA QUE O BACKUP SERÁ REALIZADO EM DISCO.
## CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT '/CAMINHO_DO_BKP/FULL_%U_%S_%P'; CONFIGURA O FORMATO DO NOME DO ARQUIVO DE BACKUP. NESSE CASO, O FORMATO É DEFINIDO COMO '/CAMINHO_DO_BKP/FULL_%U_%S_%P', ONDE '%U' É UM IDENTIFICADOR EXCLUSIVO, '%S' É UM IDENTIFICADOR SEQUENCIAL E '%P' É UM IDENTIFICADOR DO CONJUNTO DE ARQUIVOS DE BACKUP.
## CONFIGURE CONTROLFILE AUTOBACKUP ON; HABILITA O BACKUP AUTOMÁTICO DO ARQUIVO DE CONTROLE DO BANCO DE DADOS EM CADA BACKUP. ISSO GARANTE QUE UMA CÓPIA DO ARQUIVO DE CONTROLE SEJA INCLUÍDA NO BACKUP.
## BACKUP DATABASE PLUS ARCHIVELOG; REALIZA UM BACKUP COMPLETO DO BANCO DE DADOS, INCLUINDO OS ARQUIVOS DE DADOS, ARQUIVOS DE CONTROLE E ARQUIVOS DE REDO LOG. O COMANDO "PLUS ARCHIVELOG" TAMBÉM INCLUI OS ARQUIVOS DE REDO LOG ARQUIVADOS, GARANTINDO QUE TODOS OS DADOS NECESSÁRIOS PARA A RECUPERAÇÃO ESTEJAM INCLUÍDOS NO BACKUP.

## OBS: LEMBRANDO QUE EXISTEM VÁRIOS PARAMETROS DISPONÍVEIS PARA O RMAN, QUE DEVERÃO SER ALTERADOS DE ACORDO COM A NECESSIDADE
## PARA REALIZAR A VALIDAÇÃO DOS PARAMETROS DO RMAN, EXECUTAR O SEGUINTE COMANDO
## SETAR O BANCO -> RMAN TARGET / -> SHOW ALL;

## MAIS INFORMAÇÕES NA DOCUMENTAÇÃO OFICIAL
## https://docs.oracle.com/en/database/oracle/oracle-database/19/rcmrf/about-rman-commands.html#GUID-0385D88E-6D36-41AC-BEA0-DD7F5C97D253